### ISSUE TITLE
Add link to the March for Our Lives website?

### ISSUE THREAD

**Issue by joyhchen** [asg017/NeverAgainColleges#4]
I saw the comment on the right sidebar about adding a map, but I also thought we could add a link to the March for our Lives either below or above the planned map. Thoughts?

**Comment by asg017** [comment]
I love it! Theres some space to the left of the main list - link below. We can add links to website/twitter accounts for the demonstrations on april 20th and march 14th! 

https://github.com/asg017/NeverAgainColleges/blob/master/index.html#L504

**Comment by asg017** [comment]
Added functionality here: 

https://github.com/asg017/NeverAgainColleges/commit/5456a6f5395ae90decdf7010aa3ee5f79f9e1558
